Improved bump-jslib script

diff --git a/.github/workflows/bump-jslib.yml b/.github/workflows/bump-jslib.yml
--- a/.github/workflows/bump-jslib.yml
+++ b/.github/workflows/bump-jslib.yml
@@ -1,30 +1,70 @@
-name: bump-jslib
+name: Bump jslib
 
 on:
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 jobs:
-
-  # Create a jslib bump commit on the current branch
-  # Used for non-master branches
-  create-jslib-commit:
-    if: github.ref != 'refs/head/master'
+  bump-jslib:
     runs-on: ubuntu-latest
 
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+      - name: Checkout repo
+        uses: actions/checkout@v2
 
-      - name: Print job information
+      - name: setup git config
         run: |
-          echo Detected non-master branch
-          echo Creating "jslib bump" commit and pushing to branch: ${GITHUB_REF}
+          git config user.name = "GitHub Action Bot"
+          git config user.email = "<>"
 
-      # Runs a set of commands using the runners shell
       - name: Bump jslib and commit
+        id: bump
         run: |
+          TARGET_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
+          NEW_BRANCH_NAME="auto-bump-jslib"
+          OLD_JSLIB_HASH=`git submodule status | awk '{print $1}'`
+
+          if [ "$TARGET_BRANCH_NAME" = "master" ]; then
+            git checkout -b ${{ env.NEW_BRANCH_NAME }}
+            echo "[*] Checked out new branch $NEW_BRANCH_NAME"
+          fi
+
+          npm run sub:init
           npm run sub:update
+
+          git diff --quiet
+          if [ $? -eq 0]; then
+            echo "Unable to bump jslib: branch $TARGET_BRANCH_NAME is already using the latest jslib commit.""
+            exit 1
+          fi
+
           git add jslib
           git commit -m "bump jslib"
-          git push
+
+          NEW_JSLIB_HASH = `git submodule status | awk '{print $1}'`
+          echo "[*] Bumped jslib to $NEW_JSLIB_HASH"
+
+          if [ "$TARGET_BRANCH_NAME" = "master" ]; then
+            git push -u origin ${{ env.NEW_BRANCH_NAME }}
+            echo "[*] Pushed to $NEW_BRANCH_NAME"
+          else
+            git push origin ${{ env.TARGET_BRANCH_NAME }}
+            echo "[*] Pushed to $TARGET_BRANCH_NAME"
+          fi
+
+          GIT_LOG=`git log $OLD_JSLIB_HASH..$NEW_JSLIB_HASH --oneline`
+          
+          echo "::set-output name=target-branch-name::${TARGET_BRANCH_NAME}"
+          echo "::set-output name=new-branch-name::${NEW_BRANCH_NAME}"
+          echo "::set-output name=git-log::${GIT_LOG}"
+
+      - name: Submit PR against master branch
+        if: github.ref == 'refs/heads/master'
+        run: > 
+          gh pr create --title "Auto bump jslib" \
+            --body "@${{github.actor}} would like to bump jslib in this repo. This will pull in the following new commits:
+            $GIT_LOG" \
+            --reviewer eliykat 
+        env:
+          GIT_LOG: ${{ steps.bump.outputs.git-log }}
+          TARGET_BRANCH_NAME: ${{ steps.bump.outputs.target-branch-name }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
